# Generated by Django 5.0.6 on 2024-07-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isScam',
            field=models.BooleanField(default=False),
        ),
    ]
