# Generated by Django 5.0.6 on 2024-07-21 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_post_createdat_userdetails_city_userdetails_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='totalLikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='createdAt',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 15, 29, 52, 873604)),
        ),
    ]
