# Generated by Django 5.0.6 on 2024-07-21 19:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_post_totallikes_alter_post_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='totalFollowers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='createdAt',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 15, 42, 19, 166003)),
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followingSince', models.DateField(default=datetime.datetime(2024, 7, 21, 15, 42, 19, 167003))),
                ('userFollowed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='users.userdetails')),
                ('userFollower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='users.userdetails')),
            ],
        ),
    ]
