# Generated by Django 5.0.7 on 2024-08-06 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_post_spamreported_alter_friends_followingsince_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='followingSince',
            field=models.DateField(default=datetime.datetime(2024, 8, 6, 10, 49, 49, 93637)),
        ),
        migrations.AlterField(
            model_name='post',
            name='createdAt',
            field=models.DateField(default=datetime.datetime(2024, 8, 6, 10, 49, 49, 90676)),
        ),
    ]
