# Generated by Django 5.0.7 on 2024-08-06 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_friends_followingsince_alter_post_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='followingSince',
            field=models.DateField(default=datetime.datetime(2024, 8, 6, 10, 52, 0, 591998)),
        ),
        migrations.AlterField(
            model_name='post',
            name='createdAt',
            field=models.DateField(default=datetime.datetime(2024, 8, 6, 10, 52, 0, 590963)),
        ),
    ]
